
test: stdmeme.h spongeCase.c aestheticCase.c owOofCase.c aggroCase.c helpers.c test.c memef.c
	gcc helpers.c spongeCase.c aestheticCase.c owOofCase.c aggroCase.c memef.c test.c -o test

lib:
	echo "Implement later"
