
test: stdmeme.h spongeCase.c aestheticCase.c owOofCase.c aggroCase.c l33tCase.c helpers.c test.c memef.c
	gcc helpers.c spongeCase.c aestheticCase.c owOofCase.c aggroCase.c l33tCase.c memef.c test.c -o test

lib:
	echo "Implement later"

clean:
	rm test
